# Generated by Django 4.1.8 on 2023-06-09 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('bloodstock_id', models.AutoField(primary_key=True, serialize=False)),
                ('blood_group', models.CharField(max_length=3)),
                ('quantity', models.IntegerField()),
                ('last_update_date', models.DateField()),
            ],
            options={
                'db_table': 'BloodStock',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('registration_date', models.DateField()),
            ],
            options={
                'db_table': 'Donor',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('recipient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('registration_date', models.DateField()),
            ],
            options={
                'db_table': 'Recipient',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('blood_group', models.CharField(max_length=3)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodapp.donor')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodapp.recipient')),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('donation_date', models.DateField()),
                ('blood_group', models.CharField(max_length=3)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodapp.donor')),
            ],
            options={
                'db_table': 'Donation',
            },
        ),
    ]
